### ISSUE TITLE
碧蓝航线的live2d无法加载，出现如下错误

### ISSUE THREAD

**Issue by eipip1e0** [cqc233/live2dDemo#19]
大佬您好，使用碧蓝航线提取的模型的时候，我不知道我错在了哪一步，我下载您的demo，修改mapper，添加model，并在index.html中添加，然后就出现了以下错误。
```
Uncaught (in promise) TypeError: Cannot set property 'time' of undefined
    at e.parse (cubismmotion.ts:904)
    at Function.e.create (cubismmotion.ts:250)
    at e.loadMotion (cubismusermodel.ts:159)
    at lappmodel.ts:732
```
同样，在根据您csdn上的第一篇教程，使用官方最新web sdk 编译之后运行时也出现同样的错误。

然而在我使用自己制作的模型的时候就能显示出来。不知这是什么情况？望大佬解答

**Comment by cqc-elycio** [comment]
看着好像是模型的核心库报的错问题，具体我也不太清楚具体情况，方便的话能发我一份模型吗，我测试一下

**Comment by eipip1e0** [comment]
> 看着好像是模型的核心库报的错问题，具体我也不太清楚具体情况，方便的话能发我一份模型吗，我测试一下

https://github.com/Eikanya/Live2d-model/tree/master/%E7%A2%A7%E8%93%9D%E8%88%AA%E7%BA%BF%20Azue%20Lane/Azue%20Lane(JP)/lafei_4

**Comment by cqc-elycio** [comment]
可以看看我的这篇文章[Live2D(Cubism3.x)网页看板娘设置（三）](https://blog.csdn.net/qq_37735413/article/details/104857940)，参考里面关于【motions/xxx.motion3.json文件】这个的修改，改的时候保持这两个数的比值为1：2。
一般从游戏里面提取的模型会出现这个情况，估计是没完美还原模型数据

**Comment by cqc-elycio** [comment]
新版的提取工具好像没这个问题，因为我去年提取的游戏模型文件可以直接拿来用的，而你给我的那个地址里面的模型，我试了几个都不行
这个是[【Perfare】](https://github.com/Perfare/UnityLive2DExtractor)大佬的新工具

**Comment by eipip1e0** [comment]
> 新版的提取工具好像没这个问题，因为我去年提取的游戏模型文件可以直接拿来用的，而你给我的那个地址里面的模型，我试了几个都不行 这个是[【Perfare】](https://github.com/Perfare/UnityLive2DExtractor)大佬的新工具

好的，多谢
