### ISSUE TITLE
关于Hexo静态部署中的使用此live2d问题

### ISSUE THREAD

**Issue by ReverseSacle** [cqc233/live2dDemo#20]
你好，我有个问题怎么都解决不了，想请教下。
问题就是下面的图片
<img width="890" alt="屏幕截图 2021-12-23 002120" src="https://user-images.githubusercontent.com/73418195/147124483-1d41a83e-97c1-476a-b2fc-d736cad636dd.png">
<img width="261" alt="屏幕截图 2021-12-23 002537" src="https://user-images.githubusercontent.com/73418195/147124500-78a5cd1e-1583-41a1-a40b-5fc5df9cf7dc.png">
<img width="695" alt="屏幕截图 2021-12-23 002611" src="https://user-images.githubusercontent.com/73418195/147124517-d1aa41fd-e1df-4dc9-8f2d-d6b9fa4bd90a.png">
目前，我还是个前端小白，太复杂的操作不太懂，麻烦了。

**Comment by cqc-elycio** [comment]
> 你好，我有个问题怎么都解决不了，想请教下。 问题就是下面的图片 <img alt="屏幕截图 2021-12-23 002120" width="890" src="https://user-images.githubusercontent.com/73418195/147124483-1d41a83e-97c1-476a-b2fc-d736cad636dd.png"> <img alt="屏幕截图 2021-12-23 002537" width="261" src="https://user-images.githubusercontent.com/73418195/147124500-78a5cd1e-1583-41a1-a40b-5fc5df9cf7dc.png"> <img alt="屏幕截图 2021-12-23 002611" width="695" src="https://user-images.githubusercontent.com/73418195/147124517-d1aa41fd-e1df-4dc9-8f2d-d6b9fa4bd90a.png"> 目前，我还是个前端小白，太复杂的操作不太懂，麻烦了。

看情况有可能是没有找到js，你控制台看看js加载情况，应该是跟路径有关系，我没用过Hexo不清楚里面的路径要如何配置

**Comment by ReverseSacle** [comment]
@RedWolf-369 感谢回复，😂😂这个的确是我引用js文件的路径问题，是我引用方法的形式错了。另外我还有一个问题，就是我想让我的模型全身都显示出来，但canvas的范围好像已经固定了，修改.html文件中的`<canvas id="live2d" width="280" height="370" class="live2d"></canvas>`这句也只是将canvas窗口等比例缩放而已.
<img width="255" alt="屏幕截图 2021-12-23 002537" src="https://user-images.githubusercontent.com/73418195/147183496-1669810f-8cf1-43ca-9b8a-4200c984d035.png">
